// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/profiles": {
    params: {};
  };
  "/testing": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/profiles" | "/testing";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/profiles" | "/testing";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/profiles/index.tsx": {
    id: "routes/profiles/index";
    page: "/profiles";
  };
  "routes/testing.tsx": {
    id: "routes/testing";
    page: "/testing";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/profiles/index": typeof import("./app/routes/profiles/index.tsx");
  "routes/testing": typeof import("./app/routes/testing.tsx");
};